name: Update Data on SQL

on:
#  schedule:
#    - cron: '0 */3 * * *' # Run every 3 hours
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{/cloud/project/Data_Upload}}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("ggplot2","dplyr","readr","RSQLite"))'
      - name: Execute R script for validation
        run: |
          R/Load_R.R
      - name: Commit and Push Change
        run: |
          git config --global user.email "singhanirudh14@gmail.com"
          git config --global user.name "Singhanirudh14"
          git add .
          git commit -m "Write new data"
          git push
      - name: Commit files
        run: |
          git commit -m "Automate DDL Process"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.AUTOMATION_SQL_PROCESS }}
            branch: main
